graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /api/graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"
spring:
  datasource:
    url: jdbc:h2:mem:bpdev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
  flyway:
    enabled: false

