graphql:
  servlet:
    mapping: /api/graphql
    enabled: true
    corsEnabled: true
graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /api/graphql
    subscriptions: /subscriptions
  subscriptions:
    timeout: 30
    reconnect: false
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL
  cdn:
    enabled: false
    version: 0.13.0
  props:
    variables:
      editorTheme: "solarized light"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blackpearltwodev?useSSL=false&serverTimezone=UTC
    username: blackpearltwo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB

server.compression:
  enabled: true
  mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css


